version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mywebapp
      - POSTGRES_PASSWORD=mywebapp
      - POSTGRES_DB=mydatabase

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
