# Default values for the webapp Helm chart
image:
  repository: mywebapp_web
  tag: latest

service:
  port: 80
  targetPort: 5000
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"

database:
  enabled: true
  host: localhost
  port: 5432
  username: mywebapp
  password: mywebapp
  database: mydatabase

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

configMap:
  # ConfigMap data here

persistence:
  # Persistence configuration here

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

